#!/usr/bin/env python3
"""Orchestrator: run all Chinese AI media crawlers.

Runs V2EX, Juejin, 36kr, Zhihu, and WeChat media crawlers.
Generates a combined daily digest in inbox/.

Usage:
    python scripts/crawl_all.py                  # all sources
    python scripts/crawl_all.py --source v2ex     # single source
    python scripts/crawl_all.py --source 36kr --limit 10
    python scripts/crawl_all.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import datetime
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
INBOX = ROOT_DIR / "inbox"

# Available crawlers
CRAWLERS = {
    "v2ex": {
        "module": "crawl_v2ex",
        "desc": "V2EX — HN-like forum, real-time dev discussions",
        "tier": 1,
    },
    "juejin": {
        "module": "crawl_juejin",
        "desc": "掘金 — dev.to + Reddit tech subs, practical AI code",
        "tier": 1,
    },
    "36kr": {
        "module": "crawl_36kr",
        "desc": "36氪 — tech media, AI industry news & analysis",
        "tier": 1,
    },
    "zhihu": {
        "module": "crawl_zhihu",
        "desc": "知乎 — Quora-like, expert answers (target specific authors)",
        "tier": 2,
    },
    "wechat-media": {
        "module": "crawl_wechat_media",
        "desc": "微信公众号 — deep media (机器之心, PaperWeekly, 新智元)",
        "tier": 2,
    },
}


def log(msg: str) -> None:
    print(f"[crawl_all] {msg}", file=sys.stderr, flush=True)


def run_crawler(name: str, info: dict, limit: int, dry_run: bool) -> list[dict]:
    """Import and run a single crawler."""
    log(f"\n{'='*60}")
    log(f"Running: {name} — {info['desc']}")
    log(f"{'='*60}")

    try:
        import importlib
        mod = importlib.import_module(info["module"])
        argv = ["--limit", str(limit)]
        if dry_run:
            argv.append("--dry-run")
        # Some crawlers have specific fast-mode flags
        if name == "v2ex":
            argv.append("--no-replies")
        if name == "36kr":
            argv.append("--no-detail")
        return mod.main(argv)
    except Exception as exc:
        log(f"  ERROR running {name}: {exc}")
        import traceback
        traceback.print_exc(file=sys.stderr)
        return []


def write_daily_digest(all_results: dict[str, list[dict]], dry_run: bool) -> Path:
    """Write a combined daily digest markdown file."""
    today = datetime.now().strftime("%Y-%m-%d")
    path = INBOX / f"daily-digest-{today}.md"

    total = sum(len(v) for v in all_results.values())

    lines = [
        f"# 📰 Daily Digest — {today}",
        "",
        f"中国語圏 AI/LLM メディア定期監視レポート",
        "",
        f"**総記事数:** {total}",
        "",
    ]

    for source, items in all_results.items():
        if not items:
            continue
        info = CRAWLERS.get(source, {})
        desc = info.get("desc", source)
        lines.append(f"## {source} ({len(items)} 件) — {desc}")
        lines.append("")
        for i, item in enumerate(items, 1):
            title = item.get("title", "(無題)")[:80]
            url = item.get("url", "")
            author = item.get("author", "")
            tags = ", ".join(item.get("tags", [])[:4])
            line = f"{i}. **{title}**"
            if author:
                line += f" ({author})"
            if tags:
                line += f" [{tags}]"
            if url:
                line += f" — [{source}]({url})"
            lines.append(line)
        lines.append("")

    lines.append("---")
    lines.append(f"_Generated by crawl_all.py at {datetime.now().strftime('%H:%M:%S')}_")

    content = "\n".join(lines)

    if dry_run:
        log(f"[dry-run] Would write {path}")
    else:
        INBOX.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        log(f"Digest written to {path}")

    return path


def main() -> None:
    parser = argparse.ArgumentParser(description="Run all Chinese AI media crawlers")
    parser.add_argument("--source", type=str, default=None,
                        choices=list(CRAWLERS.keys()),
                        help="Run only a specific source")
    parser.add_argument("--limit", type=int, default=15,
                        help="Max items per source (default: 15)")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--tier", type=int, default=None,
                        help="Run only sources of this tier (1=primary, 2=secondary)")
    args = parser.parse_args()

    # Add scripts dir to path
    sys.path.insert(0, str(Path(__file__).resolve().parent))

    start = time.time()

    if args.source:
        sources = {args.source: CRAWLERS[args.source]}
    elif args.tier:
        sources = {k: v for k, v in CRAWLERS.items() if v["tier"] == args.tier}
    else:
        sources = CRAWLERS

    log(f"Starting crawl: {', '.join(sources.keys())} (limit={args.limit})")

    all_results: dict[str, list[dict]] = {}
    for name, info in sources.items():
        results = run_crawler(name, info, args.limit, args.dry_run)
        all_results[name] = results
        time.sleep(2)  # Brief pause between crawlers

    # Write combined digest
    write_daily_digest(all_results, args.dry_run)

    elapsed = time.time() - start
    total = sum(len(v) for v in all_results.values())
    log(f"\nAll done. {total} items from {len(sources)} sources in {elapsed:.1f}s")

    # Print summary
    print(f"\n# Crawl Summary — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"\nSources: {len(sources)} | Total items: {total} | Time: {elapsed:.1f}s\n")
    for name, items in all_results.items():
        print(f"  {name}: {len(items)} items")


if __name__ == "__main__":
    main()
